-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versione server:              10.4.28-MariaDB - mariadb.org binary distribution
-- S.O. server:                  Win64
-- HeidiSQL Versione:            12.5.0.6677
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dump della struttura del database progetto città
CREATE DATABASE IF NOT EXISTS `progetto città` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `progetto città`;

-- Dump della struttura di tabella progetto città.città
CREATE TABLE IF NOT EXISTS `città` (
  `cod` int(11) NOT NULL AUTO_INCREMENT,
  `nome` char(50) NOT NULL,
  `stato_regione` char(50) NOT NULL,
  `foto` char(50) NOT NULL,
  `descrizione` longtext NOT NULL,
  PRIMARY KEY (`cod`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='si\r\n';

-- Dump dei dati della tabella progetto città.città: ~20 rows (circa)
INSERT INTO `città` (`cod`, `nome`, `stato_regione`, `foto`, `descrizione`) VALUES
	(1, 'Bari', 'Puglia', 'bari.jpg', 'Bari, situata nella regione italiana della Puglia, è una città ricca di storia, cultura e bellezze naturali. Fondata dagli antichi romani, Bari vanta un affascinante centro storico, noto come Bari Vecchia, con stradine lastricate, chiese secolari e un lungomare pittoresco. La città è famosa per la sua autenticità e il suo vivace stile di vita mediterraneo, offrendo ai visitatori un\'esperienza indimenticabile.\r\n\r\nTre cose da vedere a Bari:\r\n\r\nBasilica di San Nicola: Questo importante luogo di culto è dedicato a San Nicola, il santo patrono di Bari, e ospita le sue reliquie. La basilica è un capolavoro dell\'architettura romanica e bizantina, con magnifici affreschi e mosaici.\r\n\r\nCastello Normanno-Svevo: Situato nel cuore del centro storico, il Castello Normanno-Svevo è una maestosa fortezza che risale al XII secolo. Oltre a essere una testimonianza della storia medievale di Bari, offre una splendida vista panoramica sulla città e sul mare Adriatico.\r\n\r\nLungomare di Bari: Questo lungomare incantevole è il luogo ideale per una piacevole passeggiata lungo il mare. Con le sue ampie strade pedonali, i caffè all\'aperto e le vedute mozzafiato sul mare, il lungomare di Bari è perfetto per rilassarsi e godersi l\'atmosfera mediterranea della città.'),
	(2, 'Bergamo', 'Lombardia', 'bergamo.jpg', 'Bergamo è una città situata nella regione italiana della Lombardia, caratterizzata dalla sua affascinante combinazione di storia, arte e bellezze naturali. Divisa in due parti distinte, la città alta e la città bassa, Bergamo offre ai visitatori una ricca varietà di attrazioni, tra cui antiche mura, chiese storiche e una vivace scena culinaria. Con i suoi stretti vicoli medievali e le piazze pittoresche, Bergamo incanta i visitatori con il suo fascino autentico e la sua atmosfera accogliente.\r\n\r\nTre cose da vedere a Bergamo:\r\n\r\nCittà Alta: Esplora il cuore storico di Bergamo nella Città Alta, circondata da imponenti mura venete. Perditi tra le strette stradine medievali, ammira le affascinanti piazze e visita luoghi iconici come la Piazza Vecchia e il Palazzo della Ragione. Non perdere l\'opportunità di salire sulla Torre del Campanone per goderti una vista panoramica spettacolare sulla città e sulle Alpi.\r\n\r\nBasilica di Santa Maria Maggiore: Questo capolavoro dell\'architettura rinascimentale e barocca è una delle chiese più importanti di Bergamo. Ammira gli straordinari affreschi di Lorenzo Lotto all\'interno della basilica e esplora il suo ricco patrimonio artistico e religioso.\r\n\r\nRocca di Bergamo: Situata sulla collina di Sant\'Eufemia, la Rocca di Bergamo è una poderosa fortezza che domina la città bassa. Risalente al IX secolo, la rocca offre una suggestiva vista panoramica su Bergamo e sulle sue circostanti valli e montagne. Esplora le sue mura imponenti, i bastioni e i giardini, e scopri la storia militare e civile della città.'),
	(3, 'Catania', 'Sicilia', 'catania.jpg', 'Catania, situata sulla costa orientale della Sicilia, è una città ricca di storia, cultura e fascino mediterraneo. Fondata nell\'VIII secolo a.C., Catania è stata plasmata da diverse influenze, dalle antiche civiltà greche e romane al periodo barocco spagnolo. La città è famosa per la sua straordinaria architettura barocca, i suoi mercati vivaci e la sua cucina deliziosa. Catania è anche dominata dalla presenza dell\'Etna, il vulcano attivo più alto d\'Europa, che conferisce alla città un paesaggio unico e suggestivo.\r\n\r\nTre cose da vedere a Catania:\r\n\r\nPiazza del Duomo: Questa maestosa piazza barocca è il cuore pulsante di Catania e ospita alcune delle sue principali attrazioni. Ammira la Fontana dell\'Elefante, simbolo della città, e visita la Cattedrale di Sant\'Agata, un capolavoro dell\'architettura barocca siciliana. Non perdere l\'opportunità di esplorare il Palazzo degli Elefanti, sede del municipio di Catania, e goderti l\'atmosfera vivace della piazza.\r\n\r\nMercato della Pescheria: Immergiti nei colori, nei profumi e nei sapori del Mercato della Pescheria, uno dei mercati più vivaci e autentici di Catania. Qui troverai una vasta selezione di prodotti locali freschi, come pesce appena pescato, frutta, verdura, formaggi e dolci tradizionali. Esplora le bancarelle, chatta con i venditori e assapora le prelibatezze locali per un\'esperienza sensoriale indimenticabile.\r\n\r\nTeatro Romano: Situato nel cuore del centro storico di Catania, il Teatro Romano è un importante sito archeologico che risale al periodo romano. Ammira la maestosità delle sue rovine, tra cui l\'orchestra, la cavea e le colonne corinzie, e scopri la storia del teatro nell\'antica Catania. Durante l\'estate, il teatro ospita spettacoli teatrali, concerti e eventi culturali, offrendo ai visitatori un\'occasione unica per immergersi nella cultura siciliana.'),
	(4, 'Costiera Amalifitana', 'Campania', 'costieramalfitana.jpg', 'La Costiera Amalfitana, situata lungo la splendida costa della regione italiana della Campania, è una delle destinazioni più affascinanti e pittoresche del mondo. Con i suoi paesaggi mozzafiato, i pittoreschi villaggi arroccati sulle scogliere e le acque cristalline del Mar Tirreno, questa regione incanta i visitatori con il suo fascino naturale e la sua ricca storia. Dichiarata Patrimonio dell\'Umanità dall\'UNESCO, la Costiera Amalfitana offre una vasta gamma di esperienze, tra cui visite a antichi siti archeologici, passeggiate panoramiche, bagni al mare e delizie culinarie.\r\n\r\nTre cose da vedere sulla Costiera Amalfitana:\r\n\r\nPositano: Questo incantevole villaggio costiero è famoso per le sue caratteristiche case color pastello, le stradine tortuose e le splendide spiagge. Esplora il centro storico di Positano, ricco di negozi di moda, boutique artigianali e ristoranti gourmet, e goditi una passeggiata lungo la spiaggia di sabbia finissima. Non perdere l\'occasione di ammirare la vista spettacolare sulla baia di Positano dall\'alto della collina.\r\n\r\nAmalfi: Questa antica città marinara è il cuore pulsante della Costiera Amalfitana e offre una ricca storia e un patrimonio culturale affascinante. Visita la magnifica Cattedrale di Sant\'Andrea, un capolavoro dell\'architettura arabo-normanna, e percorri le suggestive stradine del centro storico. Approfitta delle numerose opportunità per fare una passeggiata in barca lungo la costa e scoprire meraviglie nascoste come la Grotta dello Smeraldo.\r\n\r\nSentiero degli Dei: Questo famoso sentiero escursionistico offre una delle esperienze più spettacolari della Costiera Amalfitana. Percorri i sentieri tortuosi che si snodano lungo le scogliere, attraversando boschi di macchia mediterranea e pascoli terrazzati, e goditi panorami mozzafiato sulla costa e sulle isole circostanti. Lungo il percorso, fermati nei piccoli villaggi di Agerola e Nocelle per assaporare autentici piatti locali e incontrare la calorosa ospitalità degli abitanti del luogo.'),
	(5, 'Lecce', 'Puglia', 'lecce.jpg', 'Lecce, conosciuta come la "Firenze del Sud" per la sua straordinaria bellezza barocca, è una città situata nella regione italiana del Salento, in Puglia. Rinomata per la sua ricca storia, la sua cultura vibrante e la sua architettura mozzafiato, Lecce incanta i visitatori con i suoi dettagli artistici intricati, i suoi palazzi sontuosi e le sue chiese ornate. Esplorare le strade di Lecce significa immergersi in un mondo di arte, artigianato e tradizione, dove ogni angolo rivela un nuovo tesoro da scoprire.\r\n\r\nTre cose da vedere a Lecce:\r\n\r\nPiazza del Duomo: Situata nel cuore del centro storico di Lecce, questa spettacolare piazza è dominata dalla magnifica Cattedrale di Santa Maria Assunta. Ammira la facciata barocca della cattedrale, decorata con dettagli intricati e sculture raffinate, e visita l\'interno per ammirare gli affreschi e le opere d\'arte sacra. Passeggia lungo la piazza per ammirare anche il campanile, il palazzo vescovile e la seminario arcivescovile.\r\n\r\nBasilica di Santa Croce: Considerata il capolavoro dell\'architettura barocca leccese, la Basilica di Santa Croce è una delle chiese più straordinarie della città. Ammira la sua facciata riccamente decorata, caratterizzata da dettagli intricati, statue scolpite e motivi floreali, e esplora l\'interno per scoprire le sue splendide cappelle, altari e sculture. Non perdere l\'occasione di ammirare il soffitto a volta, decorato con affreschi e stucchi elaborati.\r\n\r\nAnfiteatro Romano: Situato nel cuore del centro storico di Lecce, l\'Anfiteatro Romano è una testimonianza vivente del passato glorioso della città. Costruito nel II secolo d.C., l\'anfiteatro è stato scoperto solo nel XX secolo e oggi rappresenta uno dei siti archeologici più importanti di Lecce. Ammira la sua struttura ellittica, circondata da case e negozi, e immergiti nella storia antica mentre esplori i suoi corridoi sotterranei e i resti delle gradinate.'),
	(6, 'Matera', 'Basilicata', 'matera.jpg', 'Matera è una città unica nel suo genere, situata nella regione italiana della Basilicata. Celebre per i suoi antichi rioni di sassi, conosciuti come "Sassi di Matera", questa città è stata abitata per millenni ed è considerata una delle più antiche continuamente abitate al mondo. I Sassi di Matera, scavati nella roccia calcarea delle colline circostanti, costituiscono un complesso di abitazioni, chiese e grotte che raccontano la storia millenaria della città. Matera è stata dichiarata Patrimonio Mondiale dell\'Umanità dall\'UNESCO e attira visitatori da tutto il mondo con il suo fascino unico e suggestivo.\r\n\r\nTre cose da vedere a Matera:\r\n\r\nSassi di Matera: Esplora i suggestivi rioni di sassi, dichiarati Patrimonio Mondiale dell\'Umanità dall\'UNESCO, che costituiscono il nucleo storico della città. Perditi tra le strette stradine e i vicoli dei Sassi, ammirando le abitazioni scavate nella roccia e le chiese rupestri millenarie. Visita la Casa Grotta, un museo che riproduce fedelmente l\'abitazione di una famiglia materana del passato, per avere un\'idea della vita quotidiana nella Matera antica.\r\n\r\nCattedrale di Matera (Duomo): Situata nel cuore del centro storico, la Cattedrale di Matera è un\'imponente chiesa che domina la città con la sua facciata romanica. All\'interno, ammira gli affreschi, le sculture e gli altari barocchi, e visita la cripta sotterranea, decorata con affreschi del XIII secolo. Dalla piazza antistante la cattedrale, goditi una splendida vista panoramica sui Sassi di Matera e sulla valle sottostante.\r\n\r\nParco della Murgia Materana: Esci dal centro storico e esplora la meravigliosa campagna circostante di Matera nel Parco della Murgia Materana. Questo parco naturale offre una varietà di sentieri escursionistici che conducono a paesaggi mozzafiato, grotte preistoriche e insediamenti rupestri. Visita il Villaggio Rupestre di Murgia Timone per scoprire gli antichi insediamenti trogloditici e ammirare la vista spettacolare sulla città di Matera.'),
	(7, 'Napoli', 'Campania', 'napoli.jpg', 'Napoli, la vivace città situata nel cuore della regione italiana della Campania, è una terra di contrasti e diversità. Con una storia che si estende per millenni, Napoli è una miscela affascinante di culture, tradizioni e stili di vita. La città è rinomata per la sua ricca arte e architettura, la sua straordinaria cucina e il suo spirito vibrante. Dai suoi antichi siti archeologici alle sue strade animate, Napoli offre ai visitatori un\'esperienza autentica e indimenticabile.\r\n\r\nTre cose da vedere a Napoli:\r\n\r\nCentro Storico: Esplora il cuore pulsante di Napoli nel suo affascinante centro storico, dichiarato Patrimonio dell\'Umanità dall\'UNESCO. Perditi tra le sue strade strette e tortuose, attraversando piazze vivaci e ammirando le chiese secolari e le case colorate. Non perdere l\'opportunità di visitare il Duomo di Napoli, il complesso monumentale di Santa Chiara e la Cappella Sansevero con il suo famoso "Cristo Velato".\r\n\r\nMuseo Archeologico Nazionale di Napoli: Scopri la straordinaria collezione di reperti archeologici dell\'antica Pompei e Ercolano presso il Museo Archeologico Nazionale di Napoli. Ammira mosaici, affreschi, statue e manufatti che risalgono all\'epoca romana, offrendo un\'incisiva visione della vita quotidiana nell\'antica Campania. Tra i pezzi più famosi vi è la collezione di oggetti provenienti dalle rovine di Pompei, tra cui i reperti dalla Villa dei Misteri e il mosaico del "Battaglione Dionisiaco".\r\n\r\nCastel dell\'Ovo e Lungomare: Goditi una passeggiata lungo il suggestivo Lungomare di Napoli, con la sua splendida vista sul Golfo di Napoli e sul Vesuvio. Fermati presso il Castel dell\'Ovo, l\'antico castello situato su un\'isola nell\'omonima baia, e ammira la sua imponente architettura e la sua storia millenaria. Da qui puoi goderti una vista spettacolare sulla città e scattare fotografie indimenticabili dei panorami circostanti.'),
	(8, 'Palermo', 'Sicilia', 'palermo.jpg', 'Palermo, la vivace capitale della Sicilia, è una città intrisa di storia, cultura e fascino mediterraneo. Con una storia che abbraccia millenni di dominazioni e influenze, Palermo è una miscela affascinante di architettura araba, normanna, barocca e rinascimentale. Dai suoi mercati vibranti alle sue maestose chiese e palazzi, Palermo offre ai visitatori un\'esperienza unica e indimenticabile. La sua cucina deliziosa, la sua gente calorosa e ospitale e la sua posizione privilegiata sul Mar Mediterraneo la rendono una delle destinazioni più affascinanti dell\'Italia meridionale.\r\n\r\nTre cose da vedere a Palermo:\r\n\r\nCattedrale di Palermo: Ammira la magnifica Cattedrale di Palermo, un capolavoro dell\'architettura normanna che mescola elementi arabi, bizantini e barocchi. Esplora l\'interno della cattedrale per ammirare i suoi affreschi, mosaici e tesori sacri, e visita la Cappella Palatina, riccamente decorata con mosaici d\'oro e preziosi manufatti.\r\n\r\nMercato della Vucciria: Immergiti nei colori, nei profumi e nei sapori del Mercato della Vucciria, uno dei mercati più vivaci e autentici di Palermo. Qui troverai una vasta selezione di prodotti locali freschi, come pesce, frutta, verdura, formaggi e dolci tradizionali. Esplora le bancarelle, chatta con i venditori e assapora le prelibatezze locali per un\'esperienza sensoriale indimenticabile.\r\n\r\nCappella Palatina: Situata all\'interno del Palazzo dei Normanni, la Cappella Palatina è un gioiello dell\'arte medievale e una delle attrazioni più importanti di Palermo. Ammira i suoi straordinari mosaici bizantini, che narrano storie della Bibbia e scene della vita di Cristo, e scopri la ricca simbologia e l\'iconografia dei suoi interni. Non perdere l\'opportunità di visitare anche il Palazzo dei Normanni e i suoi magnifici appartamenti reali.'),
	(9, 'Perugia', 'Umbria', 'perugia.jpg', 'Perugia, incastonata sulle colline umbre nel cuore dell\'Italia, è una città ricca di storia, arte e cultura. Fondata dagli antichi etruschi e successivamente dominata dai romani, Perugia vanta una ricca eredità storica e architettonica che si riflette nei suoi monumenti, nelle sue chiese e nei suoi musei. Con le sue pittoresche piazze, i suoi vicoli medievali e le sue vedute panoramiche mozzafiato, Perugia incanta i visitatori con il suo fascino autentico e la sua atmosfera rilassata.\r\n\r\nTre cose da vedere a Perugia:\r\n\r\nCentro Storico: Esplora il suggestivo centro storico di Perugia, con le sue strade lastricate, le sue piazze animate e i suoi monumenti storici. Passeggia lungo Corso Vannucci, la principale via pedonale della città, e ammira la magnifica Fontana Maggiore in Piazza IV Novembre. Visita anche la Cattedrale di San Lorenzo e il Palazzo dei Priori, sede del Museo Civico, per scoprire il ricco patrimonio artistico e culturale di Perugia.\r\n\r\nRocca Paolina: Scopri la storia medievale di Perugia visitando la Rocca Paolina, una fortezza imponente costruita nel XVI secolo per ordine del papa Paolo III. Situata nel centro della città, la Rocca Paolina offre una visione suggestiva della Perugia sotterranea, con i suoi corridoi, le sue gallerie e le sue prigioni. Ammira anche i resti delle antiche mura etrusche e romane che circondavano la città.\r\n\r\nGalleria Nazionale dell\'Umbria: Immergiti nell\'arte e nella cultura umbra presso la Galleria Nazionale dell\'Umbria, una delle più importanti collezioni d\'arte della regione. Situata all\'interno del Palazzo dei Priori, la galleria ospita opere d\'arte che spaziano dal Medioevo al Rinascimento, tra cui dipinti, sculture e manufatti artistici. Ammira capolavori di artisti umbri famosi come Pietro Perugino, Pinturicchio e il Beato Angelico, e scopri la storia e l\'arte della regione attraverso le opere esposte.'),
	(10, 'Torino', 'Piemonte', 'torino.jpg', 'Torino, la capitale del Piemonte nel nord-ovest Italia, è una città ricca di storia, cultura e bellezza architettonica. Fondata dai Romani, Torino è diventata uno dei principali centri culturali e industriali del paese. Conosciuta per la sua eleganza e il suo splendore barocco, Torino è circondata dalle maestose Alpi, che le conferiscono uno sfondo spettacolare. La città è famosa per la sua cucina deliziosa, i suoi caffè storici e la sua lunga tradizione nel campo dell\'arte e del design.\r\n\r\nTre cose da vedere a Torino:\r\n\r\nMole Antonelliana: Questo iconico simbolo di Torino è una delle torri più alte del mondo ed è sede del Museo Nazionale del Cinema. Ammira la sua maestosa architettura neogotica e goditi una vista spettacolare sulla città e sulle Alpi dal suo osservatorio panoramico. All\'interno, esplora le sale del museo dedicate alla storia del cinema, con una vasta collezione di oggetti, costumi e proiezioni cinematografiche.\r\n\r\nPalazzo Reale: Situato nel cuore del centro storico di Torino, il Palazzo Reale è una residenza reale che risale al XV secolo. Ammira la sua sontuosa architettura barocca, i suoi affreschi e le sue stanze magnificamente decorate mentre esplori le sale del palazzo. Non perdere l\'opportunità di visitare la Cappella della Sindone, che conserva la Sacra Sindone, una delle reliquie più importanti della cristianità.\r\n\r\nMuseo Egizio: Questo prestigioso museo è uno dei più grandi al mondo dedicati all\'antica civiltà egizia. Ammira una vasta collezione di reperti archeologici, tra cui mummie, sarcofagi, statue e manufatti preziosi, che offrono una visione affascinante della vita e della cultura dell\'Antico Egitto. Esplora le sale del museo per scoprire la storia delle grandi civiltà del Nilo e ammirare tesori unici come la Tomba di Kha e Merit e il Tempio di Ellesija.'),
	(11, 'Bratislava', 'Slovacchia', 'bratislava.jpg', 'Bratislava, la capitale della Slovacchia, è una città affascinante che combina il fascino dell\'Europa orientale con un\'atmosfera moderna e vibrante. Situata sulle rive del fiume Danubio, Bratislava vanta una ricca storia che risale all\'epoca romana. Con i suoi pittoreschi vicoli medievali, i suoi imponenti castelli e i suoi edifici storici, la città offre ai visitatori un\'esperienza indimenticabile. Bratislava è anche conosciuta per la sua vivace scena culturale, i suoi deliziosi piatti tradizionali e la sua calorosa ospitalità slovacca.\r\n\r\nTre cose da vedere a Bratislava:\r\n\r\nCastello di Bratislava: Dominando il panorama della città dall\'alto di una collina, il Castello di Bratislava è una delle sue attrazioni più iconiche. Questo imponente edificio storico, risalente al IX secolo, offre una vista spettacolare sulla città e sul Danubio. Esplora le sue sale e le sue mostre per scoprire la storia della Slovacchia e ammirare gli affreschi, i mobili antichi e le collezioni d\'arte.\r\n\r\nCittà Vecchia (Stare Mesto): Perditi tra le strade acciottolate della Città Vecchia di Bratislava, dove il fascino del passato si fonde con la vivacità del presente. Ammira l\'architettura gotica, barocca e rinascimentale dei suoi edifici storici, tra cui la Cattedrale di San Martino, il Municipio Vecchio e la Torre di San Michele. Esplora le sue piazze pittoresche, come la Piazza Principale (Hlavné námestie), e scopri boutique, caffè e ristoranti accoglienti lungo il percorso.\r\n\r\nMonumento a Slavin: Situato su una collina sopra la città, il Monumento a Slavin è un memoriale dedicato ai soldati sovietici che hanno combattuto per liberare Bratislava durante la Seconda Guerra Mondiale. Ammira la sua imponente statua di bronzo che rappresenta un soldato sovietico e goditi la vista panoramica sulla città circostante. Il sito è anche un luogo di quiete e riflessione, ideale per una pausa tranquilla lontano dal trambusto della città.'),
	(12, 'Bucarest', 'Romania', 'bucarest.jpg', 'Bucarest, la capitale della Romania, è una città che mescola il suo ricco patrimonio storico con un\'atmosfera cosmopolita e moderna. Situata sulle rive del fiume Dâmbovița, Bucarest è conosciuta per la sua architettura eclettica, i suoi parchi spettacolari e la sua vivace vita notturna. La città ha subito una trasformazione significativa nel corso dei secoli, passando da un piccolo insediamento medievale a una capitale europea dinamica e vivace. Oggi, Bucarest è una destinazione affascinante che offre ai visitatori un\'esperienza unica e indimenticabile.\r\n\r\nTre cose da vedere a Bucarest:\r\n\r\nPalazzo del Parlamento: Questo maestoso edificio è uno dei simboli più iconici di Bucarest e uno dei più grandi edifici amministrativi del mondo. Costruito durante il regime comunista di Nicolae Ceaușescu, il Palazzo del Parlamento è un capolavoro dell\'architettura neoclassica e offre una visione straordinaria della grandezza e del potere del regime. Oggi, il palazzo ospita il Parlamento rumeno e alcune mostre pubbliche, offrendo ai visitatori l\'opportunità di esplorare le sue magnifiche sale e sale conferenze.\r\n\r\nCentro Storico (Lipscani): Esplora il cuore storico di Bucarest nel quartiere di Lipscani, una zona ricca di storia, cultura e animazione. Passeggia lungo le strade lastricate e ammira gli edifici storici restaurati, le chiese antiche e le boutique alla moda. Lipscani è anche noto per i suoi caffè all\'aperto, i ristoranti tradizionali e le gallerie d\'arte, che offrono ai visitatori un\'ampia gamma di esperienze culturali ed enogastronomiche.\r\n\r\nParco Herastrau: Fuggi dal trambusto della città e rilassati nel Parco Herastrau, uno dei più grandi e belli parchi di Bucarest. Situato lungo le rive del lago Herastrau, il parco offre ampie aree verdi, sentieri panoramici e una varietà di attività ricreative. Noleggia una barca a remi e naviga sul lago, visita il Museo del Villaggio Rumeno per scoprire l\'architettura tradizionale rumena, o semplicemente goditi una passeggiata tranquilla lungo i sentieri ombreggiati del parco.'),
	(13, 'Budapest', 'Ungheria', 'budapest.jpg', 'Budapest, la splendida capitale dell\'Ungheria, è una città affascinante che incanta i visitatori con la sua bellezza architettonica, la sua ricca storia e le sue sorgenti termali. Situata sulle rive del fiume Danubio, Budapest è nota per i suoi impressionanti edifici storici, i suoi incantevoli ponti e i suoi bagni termali rinomati in tutto il mondo. Con i suoi quartieri vari e la sua vivace cultura, Budapest offre ai visitatori un\'esperienza indimenticabile che mescola il fascino dell\'Europa orientale con la modernità cosmopolita.\r\n\r\nTre cose da vedere a Budapest:\r\n\r\nCastello di Buda (Budavári Palota): Situato su una collina che domina il fiume Danubio, il Castello di Buda è uno dei simboli più iconici di Budapest. Questo complesso storico, che risale al XIII secolo, comprende il Palazzo Reale, la Chiesa di Mattia e la Torre del Bastione dei Pescatori, offrendo ai visitatori una panoramica della storia e della cultura ungherese. Esplora le sue sale storiche, i suoi cortili pittoreschi e ammira la splendida vista sulla città.\r\n\r\nParlamento Ungherese: Ammira l\'imponente architettura neogotica del Parlamento Ungherese, uno dei più grandi edifici parlamentari del mondo. Situato sulle rive del Danubio, il Parlamento è una delle attrazioni più famose di Budapest e offre ai visitatori l\'opportunità di esplorare le sue magnifiche sale e sale conferenze. Non perdere l\'occasione di ammirare la corona di Santo Stefano, una delle regalie più preziose dell\'Ungheria, esposta all\'interno del Parlamento.\r\n\r\nTerme di Budapest: Rilassati e rigenerati nelle famose terme di Budapest, famose in tutto il mondo per le loro proprietà curative e rilassanti. Tra le terme più rinomate vi sono le Terme di Széchenyi, le Terme di Gellért e le Terme di Rudas, ognuna con le sue piscine termali, saune e trattamenti spa. Dedica del tempo al relax e goditi una giornata di benessere immerso nelle acque calde e curative delle terme, una parte essenziale della cultura ungherese.'),
	(14, 'Cracovia', 'Polonia', 'cracovia.jpg', 'Cracovia, una delle città più antiche e affascinanti della Polonia, è un vero gioiello dell\'Europa centrale. Con una storia che risale al VII secolo, Cracovia è stata la capitale della Polonia per più di 500 anni ed è ricca di monumenti storici, architetture magnifiche e una vivace cultura. Il suo centro storico medievale, dichiarato Patrimonio dell\'Umanità dall\'UNESCO, è un labirinto di strade acciottolate, piazze storiche e chiese secolari, mentre il suo ambiente artistico e la sua animata vita notturna attirano visitatori da tutto il mondo.\r\n\r\nTre cose da vedere a Cracovia:\r\n\r\nPiazza del Mercato (Rynek Główny): Questa imponente piazza medievale è il cuore pulsante di Cracovia e una delle più grandi piazze medievali d\'Europa. Circondata da edifici storici, caffè all\'aperto e artisti di strada, la Piazza del Mercato è il luogo ideale per immergersi nell\'atmosfera vivace della città. Ammira la splendida Basilica di Santa Maria, con la sua maestosa facciata gotica e il famoso altare ligneo di Veit Stoss, e sali sulla Torre della Chiesa per goderti una vista panoramica sulla piazza e sulla città.\r\n\r\nCastello Reale di Wawel: Situato su una collina sopra il fiume Vistola, il Castello Reale di Wawel è uno dei più importanti simboli storici e culturali della Polonia. Esplora le sue magnifiche sale e cortili, ammirando gli arredi d\'epoca, le opere d\'arte e le collezioni reali. Non perdere l\'opportunità di visitare anche la Cattedrale di Wawel, dove si trovano le tombe di re e regine polacchi, tra cui quella di Re Casimiro III il Grande.\r\n\r\nQuartiere Ebraico (Kazimierz): Scopri la ricca storia ebraica di Cracovia esplorando il Quartiere Ebraico di Kazimierz, un tempo il cuore della comunità ebraica della città. Passeggia lungo le sue strade piene di carattere, scoprendo sinagoge secolari, antichi cimiteri e musei che raccontano la storia e la cultura degli ebrei polacchi. Assapora la cucina tradizionale ebraica in uno dei suoi ristoranti caratteristici e immergiti nell\'atmosfera unica di questo quartiere affascinante.'),
	(15, 'Porto', 'Portogallo', 'porto.jpg', 'Porto, la seconda città più grande del Portogallo, è una destinazione affascinante ricca di storia, cultura e bellezze naturali. Situata sulle rive del fiume Douro e conosciuta anche come "Città Invicta", Porto è famosa per i suoi affascinanti quartieri storici, i suoi monumenti storici e la sua produzione di vino porto. Con le sue strette strade acciottolate, le sue pittoresche case colorate e i suoi ponti maestosi, Porto offre ai visitatori un\'esperienza autentica e indimenticabile nel cuore del Portogallo.\r\n\r\nTre cose da vedere a Porto:\r\n\r\nPonte Dom Luís I: Questo iconico ponte in ferro è uno dei simboli più famosi di Porto e offre una vista spettacolare sulla città e sul fiume Douro. Costruito nel XIX secolo dall\'ingegnere Gustave Eiffel, il Ponte Dom Luís I collega il centro storico di Porto con il quartiere di Vila Nova de Gaia, sede delle famose cantine di vino porto. Attraversa il ponte a piedi o in tram per ammirare la sua struttura imponente e goditi una vista mozzafiato sulla città.\r\n\r\nRibeira: Esplora il pittoresco quartiere di Ribeira, situato lungo le rive del fiume Douro, dove le strette strade acciottolate e le case colorate creano un\'atmosfera incantevole. Passeggia lungo il lungofiume e scopri i numerosi caffè, ristoranti e negozi artigianali che animano le sue strade. Non perdere l\'occasione di fare una crociera sul fiume Douro o di visitare il Mercado do Bolhão, un vivace mercato coperto dove puoi assaporare prodotti locali freschi e autentici.\r\n\r\nCattedrale di Porto (Sé do Porto): Situata nel cuore del centro storico di Porto, la Cattedrale di Porto è un capolavoro dell\'architettura romanica e gotica. Ammira la sua maestosa facciata, le sue torri imponenti e il suo chiostro affascinante mentre esplori gli interni riccamente decorati. Goditi una vista panoramica sulla città dalla terrazza della cattedrale e scopri la sua storia millenaria attraverso le sue reliquie e le sue opere d\'arte sacra.\r\n\r\n\r\n\r\n\r\n\r\n'),
	(16, 'Riga', 'Lettonia', 'riga.jpg', 'Riga, la capitale della Lettonia, è una città affascinante che mescola il suo ricco patrimonio storico con un\'atmosfera moderna e cosmopolita. Situata sulle sponde del fiume Daugava, Riga è nota per la sua magnifica architettura, i suoi vivaci quartieri e la sua vibrante scena culturale. La città vanta una lunga storia che risale a oltre 800 anni, e questo si riflette nei suoi monumenti storici, nei suoi edifici medievali e nelle sue chiese secolari. Riga è anche conosciuta per la sua vivace vita notturna, i suoi ristoranti gourmet e i suoi mercati tradizionali.\r\n\r\nTre cose da vedere a Riga:\r\n\r\nVecchia Riga (Vecrīga): Esplora il cuore storico di Riga nella Vecchia Riga, un quartiere ricco di storia, architettura e fascino medievale. Passeggia lungo le sue strade acciottolate e scopri i suoi edifici storici, le sue chiese antiche e le sue piazze pittoresche. Non perdere l\'opportunità di visitare la Cattedrale di San Pietro, con la sua maestosa torre e le sue viste panoramiche sulla città, e la Casa delle Teste Nere, un edificio storico con una facciata decorata e una storia affascinante.\r\n\r\nArt Nouveau District: Ammira l\'eclettica architettura di Riga nel quartiere Art Nouveau, dove puoi trovare una delle più grandi concentrazioni di edifici in stile Art Nouveau in Europa. Esplora le strade di Elizabetes iela e Alberta iela per ammirare le facciate decorate, le sculture elaborate e i dettagli intricati di questi edifici unici. Non perdere l\'opportunità di visitare anche il Museo Riga Art Nouveau, dove puoi scoprire la storia e lo sviluppo di questo movimento artistico.\r\n\r\nMercato Centrale di Riga: Immergiti nell\'atmosfera autentica di Riga al Mercato Centrale di Riga, uno dei più grandi mercati coperti d\'Europa. Situato in cinque edifici storici di epoca nazista, il mercato offre una vasta selezione di prodotti locali freschi, carne, pesce, formaggi, pane e dolci. Esplora le sue bancarelle colorate, assapora le specialità lettoni e fai acquisti per souvenir e regali unici.'),
	(17, 'Sarajevo', 'Bosnia-Erzegovina', 'sarajevo.jpg', 'Sarajevo, la capitale della Bosnia-Erzegovina, è una città dalle profonde radici storiche e culturali, nota per la sua ricca diversità etnica e religiosa. Situata nel cuore dei Balcani, Sarajevo ha una storia complessa che abbraccia influenze ottomane, austro-ungariche e jugoslave. La città è famosa per essere stata il luogo dell\'assassinio dell\'arciduca Francesco Ferdinando nel 1914, evento che ha scatenato la Prima Guerra Mondiale. Oggi, Sarajevo è una destinazione affascinante che offre ai visitatori un mix unico di tradizioni culturali, architettura storica e ospitalità bosniaca.\r\n\r\nTre cose da vedere a Sarajevo:\r\n\r\nVecchia Bazar (Baščaršija): Esplora il cuore storico di Sarajevo nella Vecchia Bazar, un affascinante labirinto di strade acciottolate, negozi artigianali e caffè tradizionali. Risalente all\'epoca ottomana, la Baščaršija è ricca di storia e cultura e offre una straordinaria varietà di prodotti locali, come tappeti, ceramiche, gioielli e souvenir. Assapora le prelibatezze bosniache presso i suoi ristoranti e caffè e immergiti nell\'atmosfera vivace e autentica di questo quartiere affascinante.\r\n\r\nPonte Latino (Stari Most): Ammira uno dei simboli più iconici di Sarajevo, il Ponte Latino, un ponte pedonale in pietra che attraversa il fiume Miljacka. Costruito nel XVI secolo dagli Ottomani, il Ponte Latino è un esempio superbo di architettura ottomana e offre una vista panoramica sulla città vecchia. Goditi una passeggiata lungo il ponte e ammira la sua elegante struttura e le sue caratteristiche torri.\r\n\r\nTunnel di Sarajevo: Scopri una delle testimonianze più toccanti della storia recente di Sarajevo visitando il Tunnel di Sarajevo, un passaggio sotterraneo costruito durante l\'assedio della città durante la guerra della Bosnia negli anni \'90. Questo tunnel segreto, lungo circa 800 metri, collegava la città assediata con l\'aeroporto controllato dalle forze delle Nazioni Unite, consentendo il trasporto di rifornimenti vitali, armi e persino persone. Oggi, il Tunnel di Sarajevo è un museo che commemora la resistenza e la resilienza del popolo di Sarajevo durante quei tempi difficili.'),
	(18, 'Sofia', 'Bulgaria', 'sofia.jpg', 'Sofia, la capitale della Bulgaria, è una città ricca di storia, cultura e fascino. Situata ai piedi del monte Vitosha, Sofia vanta una storia che risale a oltre 2.000 anni, con influenze romane, bizantine, ottomane e sovietiche che si riflettono nel suo patrimonio architettonico e culturale. Oggi, Sofia è una metropoli moderna e cosmopolita, con vibranti quartieri urbani, musei di fama mondiale, parchi rigogliosi e una vivace vita notturna. La città offre ai visitatori un\'esperienza autentica che mescola tradizione e innovazione in un ambiente accogliente e accattivante.\r\n\r\nTre cose da vedere a Sofia:\r\n\r\nCattedrale di Alexander Nevsky: Ammira la magnifica Cattedrale di Alexander Nevsky, uno dei più grandi edifici ortodossi del mondo. Costruita per commemorare i soldati russi caduti durante la guerra russo-turca del XIX secolo, la cattedrale è un capolavoro dell\'architettura neobizantina e offre una vista mozzafiato sulla città dall\'alto delle sue cupole dorate. Esplora l\'interno della cattedrale per ammirare i suoi iconostasi, affreschi e icone sacre.\r\n\r\nPiazza della Chiesa di San Giorgio: Scopri il cuore storico di Sofia nella Piazza della Chiesa di San Giorgio, una delle piazze più belle e vivaci della città. Circondata da edifici storici, caffè accoglienti e alberi secolari, la piazza è un luogo popolare per rilassarsi, socializzare e godersi l\'atmosfera vivace della città. Ammira la splendida Chiesa di San Giorgio, con la sua architettura neobizantina e le sue caratteristiche cupole dorate, e visita il Museo Archeologico Nazionale, che ospita una vasta collezione di reperti archeologici bulgari.\r\n\r\nParco Nazionale di Vitosha: Fuggi dal trambusto della città e immergiti nella natura incontaminata del Parco Nazionale di Vitosha, situato a pochi chilometri dal centro di Sofia. Con le sue montagne imponenti, le sue foreste rigogliose e i suoi laghi cristallini, il parco offre una varietà di attività all\'aria aperta, tra cui escursioni, mountain bike, sci e arrampicata. Goditi una passeggiata panoramica lungo i sentieri del parco e ammira la bellezza selvaggia e la tranquillità della natura.'),
	(19, 'Valencia', 'Spagna', 'valencia.jpg', 'Valencia, una delle città più dinamiche e affascinanti della Spagna, è una destinazione che incanta i visitatori con la sua combinazione unica di storia, cultura, architettura moderna e tradizione mediterranea. Situata sulla costa orientale della Spagna, sulle rive del Mar Mediterraneo, Valencia è conosciuta per la sua ricca eredità storica, i suoi splendidi monumenti e la sua vibrante scena culinaria. La città vanta una lunga lista di attrazioni, tra cui antichi edifici gotici, moderni complessi architettonici, vivaci mercati e una delle più grandi aree verdi urbane d\'Europa, il Parco Turia. Con il suo clima mite, le sue spiagge mozzafiato e la sua cultura vivace, Valencia è una destinazione imperdibile per i viaggiatori in cerca di un\'esperienza autentica nel cuore della Spagna.\r\n\r\nTre cose da vedere a Valencia:\r\n\r\nCittà delle Arti e delle Scienze (Ciudad de las Artes y las Ciencias): Esplora questo straordinario complesso architettonico e culturale, progettato dall\'architetto valenciano Santiago Calatrava. La Città delle Arti e delle Scienze è composta da diversi edifici futuristici, tra cui l\'Oceanografico (il più grande acquario d\'Europa), il Museo delle Scienze Principe Felipe, l\'Emisfero (un planetario) e l\'Opera di Valencia (Palau de les Arts Reina Sofia). Ammira l\'architettura unica di Calatrava, goditi le mostre interattive e immergiti nell\'arte, nella scienza e nella cultura.\r\n\r\nCentro Storico (Ciutat Vella): Passeggia per le antiche strade della Ciutat Vella, il cuore storico di Valencia, e scopri la sua ricca storia e il suo patrimonio culturale. Ammira la maestosa Cattedrale di Valencia, esplora le affascinanti strade del Barrio del Carmen, con i suoi edifici medievali e le sue pittoresche piazze, e visita la Lonja de la Seda, un capolavoro dell\'architettura gotica che testimonia l\'importanza storica di Valencia come centro commerciale e culturale.\r\n\r\nMercato Centrale di Valencia (Mercado Central): Immergiti nei sapori e nei profumi della gastronomia valenciana al Mercado Central, uno dei mercati coperti più grandi e affascinanti d\'Europa. Situato nel cuore della città, il Mercado Central offre una vasta selezione di prodotti freschi, tra cui frutta, verdura, carne, pesce, formaggi e dolci tradizionali. Esplora le sue bancarelle colorate, assaggia le specialità locali e respira l\'atmosfera vivace di questo luogo iconico della vita quotidiana a Valencia.'),
	(20, 'Varsavia', 'Polonia', 'varsavia.jpg', 'Varsavia, la capitale della Polonia, è una città che combina il suo ricco patrimonio storico con un\'atmosfera moderna e cosmopolita. Situata sulle sponde del fiume Vistola, Varsavia ha una storia che risale a oltre 700 anni e ha subito una serie di trasformazioni nel corso dei secoli. Dopo essere stata gravemente danneggiata durante la Seconda Guerra Mondiale, la città è stata ricostruita con grande impegno e dedizione, conservando il suo carattere storico e la sua bellezza architettonica. Oggi, Varsavia è una metropoli dinamica e vivace, con musei di fama mondiale, parchi spettacolari, una vivace scena culturale e una vibrante vita notturna.\r\n\r\nTre cose da vedere a Varsavia:\r\n\r\nCittà Vecchia (Stare Miasto): Esplora il cuore storico di Varsavia nella Città Vecchia, un affascinante quartiere ricco di storia, architettura e atmosfera. Passeggia lungo le strade acciottolate e ammira gli edifici storici restaurati, le chiese secolari e le pittoresche piazze. Non perdere l\'occasione di visitare il Castello Reale di Varsavia, la Cattedrale di San Giovanni e il Museo di Varsavia, che racconta la storia della città attraverso una vasta collezione di artefatti e oggetti storici.\r\n\r\nPalazzo della Cultura e della Scienza: Ammira l\'imponente architettura del Palazzo della Cultura e della Scienza, uno dei simboli più iconici di Varsavia. Costruito negli anni \'50 come regalo dall\'Unione Sovietica alla Polonia, il palazzo è alto oltre 230 metri ed è una delle strutture più alte del paese. Salta sull\'ascensore fino alla piattaforma di osservazione per goderti una vista panoramica sulla città e scoprire l\'esposizione permanente sulle arti e le scienze polacche.\r\n\r\nParco Łazienki Królewskie (Parco Reale Łazienki): Fuggi dal trambusto della città e immergiti nella bellezza naturale del Parco Reale Łazienki, un\'oasi verde nel cuore di Varsavia. Con i suoi laghi pittoreschi, i suoi giardini lussureggianti e i suoi edifici storici, il parco è il luogo ideale per rilassarsi, fare una passeggiata o godersi un picnic. Non perdere l\'opportunità di visitare il Palazzo sull\'Isola, il Palazzo sull\'Acqua e il Palazzo Myślewicki, che ospitano una serie di mostre d\'arte e culturali durante tutto l\'anno.');

-- Dump della struttura di tabella progetto città.preferiti
CREATE TABLE IF NOT EXISTS `preferiti` (
  `cod` int(11) DEFAULT NULL,
  `username` char(50) DEFAULT NULL,
  KEY `cod` (`cod`),
  KEY `username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dump dei dati della tabella progetto città.preferiti: ~2 rows (circa)
INSERT INTO `preferiti` (`cod`, `username`) VALUES
	(1, 'ila'),
	(3, 'franci');

-- Dump della struttura di tabella progetto città.utenti
CREATE TABLE IF NOT EXISTS `utenti` (
  `nome` char(50) DEFAULT NULL,
  `cognome` char(50) DEFAULT NULL,
  `password` char(50) NOT NULL,
  `email` char(50) DEFAULT NULL,
  `username` char(50) NOT NULL,
  `comune` char(50) DEFAULT NULL,
  `indirizzo` char(50) DEFAULT NULL,
  PRIMARY KEY (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='si';

-- Dump dei dati della tabella progetto città.utenti: ~7 rows (circa)
INSERT INTO `utenti` (`nome`, `cognome`, `password`, `email`, `username`, `comune`, `indirizzo`) VALUES
	('fra', 'fraa', '', NULL, '', NULL, NULL),
	('francesca', 'tieni', 'pesca', 'frila@gmol', 'franci', 'vimezxxx', '371'),
	('ilaria', 'tieni', 'ila!', 'ilaria@gmail.com', 'ila', 'arcore', '12'),
	('ilaria', 'tieni', 'ilax', 'ilaa@franci.com', 'ilariat', 'arcorrr', 'e 209'),
	('sdf', 'sdf', 'ciao', '', 'srtdfg', '', ''),
	('francesca', 'tieni', 'sii', 'frila@gmol', 'sveva', 'vimez', '37'),
	('visss', 'hoxha', 'siv', 'jideivheiuv', 'vis', '', '');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
